name: Build and Push Docker Image on Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag to use (e.g., v1.0.0, latest, dev)"
        required: false
        default: "manual"
        type: string
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: drpcorg/nodecore
  GO_VERSION: "1.24.1"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: "1.24.1"

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      go-version: "1.24.1"

  build:
    uses: ./.github/workflows/build.yml
    with:
      go-version: "1.24.1"

  upload-release-assets:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Get short SHA
        id: short_sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Download Ubuntu artifacts
        uses: actions/download-artifact@v4
        with:
          name: nodecore-ubuntu-latest-1.24.1-${{ steps.short_sha.outputs.sha }}
          path: ./artifacts/ubuntu

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: nodecore-macos-latest-1.24.1-${{ steps.short_sha.outputs.sha }}
          path: ./artifacts/macos

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          # Rename and move artifacts
          cp ./artifacts/ubuntu/nodecore ./release-assets/nodecore-linux-amd64
          cp ./artifacts/macos/nodecore ./release-assets/nodecore-darwin-amd64

          # Make them executable
          chmod +x ./release-assets/*

          # List what we have
          ls -la ./release-assets/

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release-assets/nodecore-linux-amd64
            ./release-assets/nodecore-darwin-amd64

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, lint, build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=raw,value=${{ inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Debug metadata
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=gha,scope=docker-build
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: |
            type=gha,mode=max,scope=docker-build
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
