name: Lint

on:
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
      - main

env:
  GO_VERSION: "1.24.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Go project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-key-suffix: "lint"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout=10m
          skip-cache: false
