name: Run tests

on:
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
      - main

env:
  GO_VERSION: "1.24.1"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.1", "1.23.x"]
    steps:
      - name: Setup Go project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ matrix.go-version }}
          cache-key-suffix: "test"

      - name: Run tests
        run: make test
