upstream-config:
  upstreams:
    - id: eth-upstream
      chain: polygon
      failsafe-config:
        retry:
          attempts: 3
          max-delay: 5s
          delay: 10s
      connectors:
        - type: json-rpc
          url: https://test.com