server:
  port: 9095
  pprof-port: 6061
  metrics-port: 9093

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      connectors:
        - type: json-rpc
          url: https://test.com