server:
  port: 9095

cache:
  connectors:
    - id: memory-connector
      driver: memory
      memory:
        max-items: 1000
        expired-remove-interval: 10s
  policies:
    - chain: "optimism|polygon | ethereum"
      id: super_policy
      method: "*getBlock*"
      finalization-type: none
      cache-empty: true
      connector-id: memory-connector
      object-max-size: "10KB"
      ttl: 10s

upstream-config:
  failsafe-config:
    retry:
      attempts: 10
      delay: 2s
      max-delay: 5s
      jitter: 3s
    hedge:
      delay: 500ms
      max: 2
  chain-defaults:
    ethereum:
      poll-interval: 2m
  upstreams:
    - id: eth-upstream
      chain: ethereum
      head-connector: websocket
      poll-interval: 3m
      failsafe-config:
        retry:
          attempts: 5
          delay: 500ms
          max-delay: 1s
          jitter: 6s
      connectors:
        - type: json-rpc
          url: https://test.com
          headers:
            Key: Value
        - type: websocket
          url: wss://test.com
    - id: another
      chain: polygon
      failsafe-config:
        retry:
          attempts: 7
      connectors:
        - type: rest
          url: https://test.com
        - type: grpc
          url: https://test-grpc.com
          headers:
            key: value